
server:
  port: 8763

spring:
  application:
    name: cloud-client-2

foo: 12345678889990000-------

management:
  security:
    enabled: false
    
spring:
  rabbitmq:
    host: 47.100.169.40
    port: 5672
    username: admin
    password: admin
