
server:
  port: 8763

spring:
  application:
    name: cloud-client-2

foo: 1234567888999

management:
  security:
    enabled: false
    
#spring:
#  rabbitmq:
#    host: 47.100.169.40
#    port: 15672
#    username: admin
#    password: admin
